---
title: "Untitled"
author: "RLD"
date: "12/15/2016"
output: html_document
---

```{r}
to.plot.df <- data.frame('model'=c('Always 1', 'Always 1', 'Always 1', 'Always 1', 'Average', 'Average', 'Average', 'Average', 'Naive Bernoulli', 'Naive Bernoulli', 'Naive Bernoulli', 'Naive Bernoulli', 'Logistic Regression', 'Logistic Regression', 'Logistic Regression', 'Logistic Regression', 'BKT', 'BKT', 'BKT', 'BKT', 'Clustered BKT', 'Clustered BKT', 'Clustered BKT', 'Clustered BKT'), 'data'=c('Synthetic BKT', 'Synthetic IRT', 'KDD', 'Assistments', 'Synthetic BKT', 'Synthetic IRT', 'KDD', 'Assistments', 'Synthetic BKT', 'Synthetic IRT', 'KDD', 'Assistments', 'Synthetic BKT', 'Synthetic IRT', 'KDD', 'Assistments', 'Synthetic BKT', 'Synthetic IRT', 'KDD', 'Assistments', 'Synthetic BKT', 'Synthetic IRT', 'KDD', 'Assistments'), 'N'=100, 'AUC'=c(0.5, 0.5, 0.5, 0.5, 0.833, 0.954, 0.644, 0.732, 0.708, 0.601, 0.623, 0.584, 0.787, 0.874, 0.638, 0.585, 0.878, 0.952, 0.762, 0.781, 0.876, 0.953, 0.764, 0.747), 'sd' = c(0,0,0,0,0.0337044079656918,0.00773230359351618,0.00858568382114726,0.0360706918157734,0.0518511322754785,0.0258678273944831,0.0183623467019337,0.0375617646556907,0.0353684360418452,0.0215805141682849,0.0171885333603422,0.0398198541271807,0.0272101212567812,0.00521417212272578,0.00928629026254340,0.0280538742622537,0.0276133785181447,0.00506937766713000,0.00907635253696966,0.0348107952395288))
```

```{r}
library(ggplot2)
pd <- position_dodge(0.9) # move them .05 to the left and right
ggplot(to.plot.df, aes(x=data, y=AUC, group=as.factor(model), color=as.factor(model))) +
  geom_errorbar(aes(ymin=AUC-sd, ymax=AUC+sd), width=.2, position=pd) +
  geom_point(position=pd) + 
  #geom_line(position=pd) + 
  xlab("X") + ylab("Y") + 
  ggtitle("TITLE")
```

```{r}
library(ggplot2)
pd <- position_dodge(0.7) # move them .05 to the left and right
ggplot(to.plot.df, aes(x=data, y=AUC, fill=model)) + geom_col(position=pd, width=0.7) + 
  geom_errorbar(aes(ymin=AUC-sd, ymax=AUC+sd), width=0.2, position=pd, color="black") + 
  scale_fill_brewer(palette='Paired') + 
  #scale_fill_manual(values=c("#00ffff", "#0077ff", "#0000ff", "#7700ff", "#ff00ff", "#ff0077")) 
  #geom_line(position=pd) + 
  xlab("Dataset") + #ylab("Y") + 
  ggtitle("Per-Model, Per-Dataset AUC (Error bars show Standard Deviation)")
```
